### ISSUE TITLE
little typo

### ISSUE THREAD

**Issue by zeke** [iandevlin/iandevlin.com#1]
👋 @iandevlin 

Great post on `:focus-within`: https://www.iandevlin.com/blog/2017/04/css/the-focus-within-pseudo-class?utm_source=frontendfocus&utm_medium=email

I found a typo: "came across the a new CSS"

**Comment by iandevlin** [comment]
Thanks! I only saw this comment now, and have updated the post. Thanks again.

**Comment by zeke** [comment]
👍
